contacts:
  name: Zoë Courvoisier-Clément
  title: "Étudiant de 2ᵉ année d'étude d'ingénieur à l'ESISAR"
  email: pro.courvoisier@gmail.com
  phone: "06 66 05 77 47"
  address: "26000 Valence, France"
  mobility: "bus, train"
  nationality: Française
  github: "blokyk"

bio: >
  Outre être un étudiant de 3ᵉ année d'étude d'ingénieur à l'ESISAR, je suis
  surtout une personne animée par sa passion pour la programmation, sa
  curiosité insatiable, et sa playlist journalière.

skills:
  - name: Langues
    items:
      - Français
      - Anglais (Cambridge C1, TOEIC C1)
  - name: Langages de programmation
    items:
      - C#
      - C
      - Dart/Flutter
      - Haskell
      - GLSL
      - Go
      - Python
      - VHDL
  - name: Outils
    items:
      - VS Code
      - Visual Studio 2025
      - Git
      - GitHub/GitLab
  - name: Autres
    items:
      - Linux administration

jobs:
    # tags:
  - position: Stagiaire du service informatique
    company:
      name: Faurecia
      link: https://faurecia.com/
    from: "Juin"
    to: "Juillet 2018"
    description:
      - Repaired employees' computers
      - Checked server status
      - Helped employees with miscellaneous computer problems

  - position: Research internship
    company:
      name: LCIS laboratory
      link: https://lcis.fr
    from: "2024 June"
    to: "2024 August"
    description:
      - Built a modified RISC-V toolchain for the RISC-V Vector (RVV) extension
      - Surveyed the state-of-the-art of RVV co-processor designs
      - Manually vectorized (in both AVX and RVV) data-processing algorithms
      - Setup benchmarks comparing the performance of vectorized vs scalar code
      - Worked with a team of interns and researchers on a nation-wide project

education:
  - university:
      name: Esisar – Grenoble INP
      link: "https://esisar.grenoble-inp.fr/"
    degree: "Engineering degree"
    description: >
      Computer science, cybersecurity, networking, operating systems, embedded development

      (Currently in my fourth year overall.)
    from: "2021"
    to: "2026"

projects:
  - project:
      name: StarKid
      #link: "https://github.com/blokyk/starkid"
      tags:
        - C#
        - Developper tooling
        - CLI
    description: >
      A C# package that allows creating full-featured command-line apps
      by simply describing the accepted options, arguments and commands
      with normal C# fields and methods. StarKid then generates the
      corresponding argument parser at compile-time using Roslyn source
      generators.
    from: "2022"
    to: "present"
  - project:
      name: Lotus
      link: https://github.com/lotuslang/lotus
      tags:
        - C#
        - Compiler
        - Parsing
        - Language Design
    description: >
      A custom programming language, designed and implemented entirely by
      myself from the ground up. Still in the early stages (currently working
      on the type system). In practice, the focus is mainly on being able to
      give clear (Elm- or Rust-style) error messages.
    from: "2020"
    to: "present"
  - project:
      name: RISC-V Emulator
      link: "https://github.com/blokyk/px-cs351"
      tags:
        - C
        - RISC-V Assembly
        - Testing
    description: >
      A RISC-V assembler & emulator written in C, implementing the basic RV64-I
      instruction set. Written in the context of course CS351, with a focus on
      testing and accuracy. Implementation-wise, smart use of macros and
      preprocessor tricks allowed an extensible, declarative way to specify
      instructions. Modifying a reference emulator allowed fuzzing-like testing
      and validation of the implementation.
    from: "October 2023"
    to: "January 2024"
  - project:
      name: AES Implementation
      link: "https://github.com/blokyk/px222-aes"
      tags:
        - Cryptography
        - Haskell
        - C
    description: >
      A pair of AES implementations, one written in Haskell, using mathematical
      formalism (fields, polynomials, etc) to model byte-level arithmetic, and
      one written in C, with a large focus on performance and optimisation.
      Also wrote a test framework for the Haskell version.
    from: "March 2023"
    to: "June 2023"
  - project:
      name: Youth teaching volunteer
      tags:
        - Education
        - Youth
        - Teamwork
    description: >
      Volunteered to help younger, impoverished students with their homework
      after school, sometimes teaching key concepts to an entire group, and
      sometimes working one-on-one with each student. (Wow this feels VERY
      exploitative to write.)
    from: "September 2022"
    to: "May 2023"