contacts:
  name: Zoë Courvoisier-Clément
  title: Third-year engineering student at ESISAR school
  email: pro@zoeee.net
  phone: "+33 6 66 05 77 47"
  # address: "26000 Valence, France"
  mobility: "bus, train"
  nationality: French
  github: "blokyk"

bio: >
  Aside from being a third-year student at the ESISAR engineering school,
  I'm mostly someone driven by my passion for coding, my boundless curiosity,
  and my daily playlist.

skills:
  - name: Spoken Languages
    items:
      - French (Native)
      - English (Cambridge C1 level)
  - name: Programming Languages
    items:
      - C#
      - C
      - Dart/Flutter
      - Haskell
      - GLSL
      - Go
      - Python
      - VHDL
  - name: Tools
    items:
      - VS Code
      - Visual Studio 2025
      - Git
      - GitHub/GitLab
  - name: Miscellaneous
    items:
      - Linux administration

jobs:
  - position: Research internship
    company:
      name: LCIS laboratory
      link: https://lcis.fr
    from: "June"
    to: "August 2024"
    description:
      - Built a modified RISC-V toolchain for the Vector (RVV) extension
      - Surveyed the state-of-the-art of RVV co-processor hardware designs
      - Manually vectorized (in both AVX and RVV) data-processing algorithms
      - Measured and compared the performance of vectorized vs scalar variants
      - Worked with a team of interns and researchers on a national project
  - position: Full-stack & mobile developer
    company:
      name: Olorin
      link: "https://olorin-web3.com/"
    from: "January"
    to: "July 2025"
    description:
      - Took the company's concept from idea to MVP
      - Fleshed out a basic back-end architecture (ASP.NET Core + PostgreSQL)
      - Explored cross-platform frameworks to find the most suitable (Flutter)
      - Wrote platform-specific code interacting with unreleased NFC technology
      - Took great care to maximize users' privacy, using novel key-exchange
        protocols and other cryptographic techniques
      - Collaborated with UI/UX designer to develop a truly modern interface
      - Corrected roadmap to adapt to production delays and changing budget

education:
  - university:
      name: Esisar – Grenoble INP
      link: "https://esisar.grenoble-inp.fr/"
    degree: "Engineering degree"
    description: >
      Computer science, cybersecurity, networking, operating systems, embedded development

      (Currently in my fifth year overall.)
    from: "2021"
    to: "2026"
  - university:
      name: University of Porto
      link: "https://www.up.pt/fcup/en/"
    degree: "Computer Science M1        "
    description: >
      Computer science, computer vision, cryptography. Spent half a year there for as an ERASMUS student.
    from: "September 2025"
    to: "February 2026"

projects:
  - project:
      name: StarKid
      link: "https://github.com/blokyk/starkid"
      tags:
        - C#
        - Developer tooling
        - CLI
    description: >
      A C# package that allows creating full-featured command-line apps
      by simply describing the accepted options, arguments and commands
      with normal C# fields and methods. StarKid then generates the
      corresponding argument parser at compile-time using Roslyn source
      generators.
    from: "2022"
    to: "2025"
  - project:
      name: Lotus
      link: https://github.com/lotuslang/lotus
      tags:
        - C#
        - Compiler
        - Parsing
        - Language Design
    description: >
      A custom programming language, designed and implemented entirely by
      myself from the ground up. Still in the early stages (currently working
      on the type system). In practice, the focus is mainly on being able to
      give clear (Elm- or Rust-style) error messages.
    from: "2020"
    to: "present"
  - project:
      name: RISC-V Emulator
      link: "https://github.com/blokyk/px-cs351"
      tags:
        - C
        - RISC-V Assembly
        - Testing
    description: >
      A RISC-V assembler & emulator written in C, implementing the basic RV64-I
      instruction set. Written in the context of course CS351, with a focus on
      testing and accuracy. Implementation-wise, smart use of macros and
      preprocessor tricks allowed an extensible, declarative way to specify
      instructions. Modifying a reference emulator allowed fuzzing-like testing
      and validation of the implementation.
    from: "October 2023"
    to: "January 2024"
  - project:
      name: AES Implementation
      link: "https://github.com/blokyk/px222-aes"
      tags:
        - Cryptography
        - Haskell
        - C
    description: >
      A pair of AES implementations, one written in Haskell, using mathematical
      formalism (fields, polynomials, etc) to model byte-level arithmetic, and
      one written in C, with a large focus on performance and optimisation.
      Also wrote a test framework for the Haskell version.
    from: "March 2023"
    to: "June 2023"
  - project:
      name: Youth teaching volunteer
      tags:
        - Education
        - Youth
        - Teamwork
    description: >
      Volunteered to help younger, impoverished students with their homework
      after school, sometimes teaching key concepts to an entire group, and
      sometimes working one-on-one with each student. (Wow this feels VERY
      exploitative to write.)
    from: "September 2022"
    to: "May 2023"