font:
  size:
    heading_huge: 19pt
    heading_large: 16pt
    heading: 13pt
    description: 10pt
    tags: 10pt
    education_description: 8pt
    contacts: 8pt
  general: "Libertinus Serif"
  minor_highlight: "Libertinus Serif"

paragraph:
  # Distance between lines
  leading: 4pt

lang: fr